### ISSUE TITLE
Specifying relay count still causes relays to be reset

### ISSUE THREAD

**Issue by amorphic** [amorphic/tosr0x#5]
As per [this comment](http://jimter.net/controlling-a-tosr0x-usb-relay-module-using-python/#comment-2017963131), apparently the call `serialDevice = serial.Serial(devicePath, timeout=2)` causes a reset to 0 of all relays regardless of whether or not the relay count is passed.

**Comment by amorphic** [comment]
I will try to reproduce this and if I can I'll fix it and release an update.

**Comment by amorphic** [comment]
As per `README.md`, the `relayCount` may now be specified in the handler:

>Usually all relays on the module are cycled at initialisation to determine the relay count. You can specify a relay count to prevent this:

    >th = tosr0x.handler(devicePath=['/dev/ttyUSB3'], relayCount=4)

    Testing USB serial device on /dev/ttyUSB3
    TOSR0x device found on /dev/ttyUSB3

**Comment by paoletto** [comment]
jesus.. do you think I'm an idiot? i already specified the‎ relay count. can't you even read the subject of the issue?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: James StewartSent: Tuesday, June 2, 2015 01:08To: amorphic/tosr0xReply To: amorphic/tosr0xCc: paolettoSubject: Re: [tosr0x] Specifying relay count still causes relays to be reset (#5)As per README.md, the relayCount may now be specified in the handler:


Usually all relays on the module are cycled at initialisation to determine the relay count. You can specify a relay count to prevent this:


>th = tosr0x.handler(devicePath=['/dev/ttyUSB3'], relayCount=4)

Testing USB serial device on /dev/ttyUSB3
TOSR0x device found on /dev/ttyUSB3


—Reply to this email directly or view it on GitHub.

**Comment by paoletto** [comment]
well ok sorry for the tone. I guess i was nervous this morning. Anyway, i
think the problem is caused by opening the serial.. unless my tosr is
defective, of course..

**Comment by amorphic** [comment]
I hope you've had your morning coffee and you're feeling a little better...;)

Make sure you're using the latest version of the tosr0x package, (0.5.2).

Using my 4-relay tosr0x, I can do the following. No relays are activated until step 5 when I switch on relay 2:

```python
In [1]: import tosr0x
In [2]: import serial
In [3]: s = serial.Serial('/dev/ttyUSB1')
In [4]: t = tosr0x.relayModule(s, relayCount=4)
In [5]: t.set_relay_position(2,1)
Out[5]: True
```

I can also now do the following using the handler. No relays are activated until step 3 when I switch on relay 2:

```python
In [1]: import tosr0x
In [2]: t = tosr0x.handler(relayCount=4)[0]
In [3]: t.set_relay_position(2,1)
Out[3]: True
```

I notice that if a relay is switched on, it is turned off when I do the following:

```python
In [1]: import serial
In [3]: s = serial.Serial('/dev/ttyUSB1')
```

I have a feeling that when a `serial.Serial` object is created, the serial connection is probably initialised and this causes the relays to turn off. But this is beyond the control of `tosr0x.py`.

**Comment by paoletto** [comment]
i see.. well that's actually the bug i am facing, as my script has to initialize everything everytime ( it reacts on event such as inet not working -> modem reboot needed).i agree that if you experience it too, it must be pyserial fault. I'll see if i can figure this out somehow..I hope you've had your morning coffee and you're feeling a little better...;)

Make sure you're using the latest version of the tosr0x package, (0.5.2).

Using my 4-relay tosr0x, I can do the following. No relays are activated until step 5 when I switch on relay 2:

In [1]: import tosr0x
In [2]: import serial
In [3]: s = serial.Serial('/dev/ttyUSB1')
In [4]: t = tosr0x.relayModule(s, relayCount=4)
In [5]: t.set_relay_position(2,1)
Out[5]: True

I can also now do the following using the handler. No relays are activated until step 3 when I switch on relay 2:

In [1]: import tosr0x
In [2]: t = tosr0x.handler(relayCount=4)[0]
In [3]: t.set_relay_position(2,1)
Out[3]: True

I notice that if a relay is switched on, it is turned off when I do the following:

In [1]: import serial
In [3]: s = serial.Serial('/dev/ttyUSB1')

I have a feeling that when a serial.Serial object is created, the serial connection is probably initialised and this causes the relays to turn off. But this is beyond the control of tosr0x.py.
